name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        
        - python: "3.12"
          toxenv: py312
          
        - python: "3.11"
          toxenv: py311
          
        - python: "3.10"
          toxenv: py310
          
        - python: "3.9"
          toxenv: py39
          
        - python: "3.8"
          toxenv: py38
      
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: python -m pip install -U tox

      - name: Tox tests
        run: tox -e ${{ matrix.toxenv }}
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Any Name Bash Test Step
        shell: bash
        run: echo "hola"